---
output:
  pdf_document: default
  html_document: default
---

## Part B : Local MDS, ISOMAP and t-SNE.

### 2. Local MDS for ZERO digits.

```{r}

if (!require("smacofx", quietly = TRUE, warn.conflicts = FALSE)) {
  install.packages("smacofx", repos = "http://R-Forge.R-project.org", INSTALL_opts = "--no-test-load")
}

library("smacofx")

if (!require(stops, quietly=TRUE, warn.conflicts=FALSE)){
  install.packages("stops", repos="http://R-Forge.R-project.org",INSTALL_opts="--no-test-load")
}

library(stops)

plot.zip <- function(x,use.first=FALSE,...){
  x<-as.numeric(x)
  if (use.first){
    x.mat <- matrix(x,16,16)
  }else{
    x.mat <- matrix(x[-1],16,16)
  }
  image(1:16,1:16,x.mat[,16:1],
        col=gray(seq(1,0,l=12)),...)
  invisible(
    if (!use.first){
      title(x[1])
    }else{
    }
  )  
  #col=gray(seq(1,0,l=2)))
}

# Load the entire training data set
data <- read.table("zip.train", sep=" ")

# Separate the target labels and feature vectors
labels <- data$V1
features <- data[, -1]

# Filter only the ZEROs (label 0)
zero_indices <- which(labels == 0)
zero_data <- features[zero_indices,]

plot.zip(zero_data[1,])

```

### a).

```{r}
n <- dim(zero_data)[1]
k <- 5
tau <- .05
q<-2 # 2-dim config
conf0 <- stats::cmdscale(dist(zero_data), k=q)


lmds_result <- lmds(as.matrix(dist(zero_data)), init=conf0, ndim=2, k=5, tau=0.05, itmax = 1000)

ylower_limit <- min(lmds_result$conf[, 2]) - 0.1
yupper_limit <- max(lmds_result$conf[, 2]) + 0.1

xlower_limit <- min(lmds_result$conf[, 1]) - 0.1
xupper_limit <- max(lmds_result$conf[, 1]) + 0.1


plot(lmds_result$conf, type = "n", xlab = "Dimension 1", ylab = "Dimension 2", main = "LMDS Scatterplot", ylim = c(ylower_limit, yupper_limit), xlim=c(xlower_limit, xupper_limit))


points(lmds_result$conf, pch = 20, col = "blue")


selected_indices <- c(31, 380, 106, 53, 7, 559, 22, 259, 410)

selected_points <- lmds_result$conf[selected_indices, ]



plot(lmds_result$conf, type = "n", xlab = "Dimension 1", ylab = "Dimension 2", main = "LMDS Scatterplot")

points(selected_points, pch = 20, col = "blue")
text(selected_points, labels = selected_indices, pos = 3, cex = 0.7)

```

### b).

```{r}

for (i in 1:9) {
  cat("Image for Point ", selected_indices[i], ":\n")
  plot.zip(zero_data[selected_indices[i], ])
  cat("\n")
}
```

### c).

```{r}
k_values <- c(5, 10, 50)
tau_values <- c(0.1, 0.5, 1)

best_k <- NULL
best_tau <- NULL
best_stress <- Inf  

best_configuration <- NULL

for (k in k_values) {
  for (tau in tau_values) {
    lmds_result <- lmds(as.matrix(dist(zero_data)), ndim = 2, k = k, tau = tau, itmax=1000)
    
    stress <- lmds_result$stress
    
    if (stress < best_stress) {
      best_stress <- stress
      best_k <- k
      best_tau <- tau
      best_configuration <- lmds_result$conf
    }
  }
}

cat("Best Configuration - k:", best_k, "tau:", best_tau, "Stress:", best_stress, "\n")

plot(best_configuration, xlab = "Dimension 1", ylab = "Dimension 2", main = "Optimal Low-Dimensional Configuration")
```

