---
output:
  pdf_document: default
  html_document: default
---

### 3 ISOMAP for ZERO digits.

### a).

```{r}

plot.zip <- function(x,use.first=FALSE,...){
  x<-as.numeric(x)
  if (use.first){
    x.mat <- matrix(x,16,16)
  }else{
    x.mat <- matrix(x[-1],16,16)
  }
  image(1:16,1:16,x.mat[,16:1],
        col=gray(seq(1,0,l=12)),...)
  invisible(
    if (!use.first){
      title(x[1])
    }else{
    }
  )  
  #col=gray(seq(1,0,l=2)))
}


data <- read.table("zip.train", sep=" ")

# Separate the target labels and feature vectors
labels <- data$V1
features <- data[, -1]

# Filter only the ZEROs (label 0)
zero_indices <- which(labels == 0)
zero_data <- features[zero_indices,]

library(vegan)


isomap_result <- isomap(as.matrix(dist(zero_data)), ndim = 2, k = 5)

isomap_coordinates <- isomap_result$points

plot(isomap_coordinates, type = "n", xlab = "Dimension 1", ylab = "Dimension 2", main = "Isomap 2-Dimensional Configuration")

points(isomap_coordinates, pch = 20, col = "blue")

selected_indices <- c(1170, 891, 938, 357, 75, 9, 596, 779, 654)

selected_points <- isomap_coordinates[selected_indices, ]

plot(selected_points, type = "n", xlab = "Dimension 1", ylab = "Dimension 2", main = "Selected Isomap 2-Dimensional Configuration")

points(selected_points, pch = 20, col = "blue")

text(selected_points, labels = selected_indices, pos = 3, cex = 0.7)
```


### b).

```{r}
for (i in 1:9) {
  cat("Image for Point ", selected_indices[i], ":\n")
  plot.zip(zero_data[selected_indices[i], ])
  cat("\n")
}
```

### c).

```{r}

```
