---
title: "question4"
date: "2023-10-22"
output: html_document
---

### 4 t-SNE for ZERO digits.

### a).

```{r}
plot.zip <- function(x,use.first=FALSE,...){
  x<-as.numeric(x)
  if (use.first){
    x.mat <- matrix(x,16,16)
  }else{
    x.mat <- matrix(x[-1],16,16)
  }
  image(1:16,1:16,x.mat[,16:1],
        col=gray(seq(1,0,l=12)),...)
  #col=gray(seq(1,0,l=2)))
}


data <- read.table("zip.train", sep=" ")

# Separate the target labels and feature vectors
labels <- data$V1
features <- data[, -1]

# Filter only the ZEROs (label 0)
zero_indices <- which(labels == 0)
zero_data <- features[zero_indices,]
```

```{r}
#install.packages("Rtsne")
library(Rtsne)

set.seed(1)
tsne_out <- Rtsne(zero_data[,-ncol(zero_data)],dims=2,pca=FALSE,perplexity=40,theta=0.0) # Run TSNE

# Scatterplot of 2D tsne representation
plot(tsne_out$Y, asp=1)
```

### b).

```{r}
interesting_points <- c(which(tsne_out$Y[,1]==min(tsne_out$Y[,1])))
interesting_points <- c(interesting_points,which(tsne_out$Y[,1]==quantile(tsne_out$Y[,1], 0.25, type=1)))
interesting_points <- c(interesting_points,which(tsne_out$Y[,1]==quantile(tsne_out$Y[,1], 0.5, type=1)))
interesting_points <- c(interesting_points,which(tsne_out$Y[,1]==quantile(tsne_out$Y[,1], 0.75, type=1)))
interesting_points <- c(interesting_points,which(tsne_out$Y[,1]==max(tsne_out$Y[,1])))

interesting_points <- c(interesting_points,which(tsne_out$Y[,2]==min(tsne_out$Y[,2])))
interesting_points <- c(interesting_points,which(tsne_out$Y[,2]==quantile(tsne_out$Y[,2], 0.25, type=1)))
interesting_points <- c(interesting_points,which(tsne_out$Y[,2]==quantile(tsne_out$Y[,2], 0.5, type=1)))
interesting_points <- c(interesting_points,which(tsne_out$Y[,2]==quantile(tsne_out$Y[,2], 0.75, type=1)))
interesting_points <- c(interesting_points,which(tsne_out$Y[,2]==max(tsne_out$Y[,2])))

plot(tsne_out$Y, asp=1)
points(tsne_out$Y[interesting_points,1],tsne_out$Y[interesting_points,2],col = "red", pch=19)
text(tsne_out$Y[interesting_points,1],tsne_out$Y[interesting_points,2],labels = interesting_points, pos = 3, cex = 0.7, col = "red")
```

```{r}
for (i in 1:5) {
  cat("Image for Point ", interesting_points[i], ":\n")
  plot.zip(zero_data[interesting_points[i], ])
  title(interesting_points[i])
}
```
```{r}
for (i in 6:10) {
  cat("Image for Point ", interesting_points[i], ":\n")
  plot.zip(zero_data[interesting_points[i], ])
  title(interesting_points[i])
}
```

### c).

```{r}
LCMC <- function(D1,D2,Kp){
  D1 <- as.matrix(D1)
  D2 <- as.matrix(D2)
  n <- dim(D1)[1]
  N.Kp.i <- numeric(n)
  for (i in 1:n){
    N1.i <- sort.int(D1[i,],index.return = TRUE)$ix[1:Kp]
    N2.i <- sort.int(D2[i,],index.return = TRUE)$ix[1:Kp]
    N.Kp.i[i] <- length(intersect(N1.i, N2.i))
  }
  N.Kp<-mean(N.Kp.i)
  M.Kp.adj <- N.Kp/Kp - Kp/(n-1)
  
  return(list(N.Kp.i=N.Kp.i, M.Kp.adj=M.Kp.adj))
}
```
